from enum import Enum

class PASSPORT_TYPE(str, Enum):
	OPEN = "OPEN"
	CLOSED = "CLOSED"

class PASSPORT_STATUS(str, Enum):
	ACTIVE = "ACTIVE"
	INACTIVE = "INACTIVE"
	CONSUMED = "CONSUMED"
	REVOKED = "REVOKED"
	EXPIRED = "EXPIRED"
	SUSPENDED = "SUSPENDED"
	EXHAUSTED = "EXHAUSTED"